# Generated by Django 3.1.3 on 2020-11-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aficion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAficion', models.CharField(max_length=50)),
                ('edadMedia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estimacionSeguidores', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiudad', models.CharField(max_length=25)),
                ('provincia', models.CharField(max_length=40)),
                ('comunidad', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstadoCivil', models.CharField(max_length=20)),
                ('representacion', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombreUsuario', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidoUno', models.CharField(max_length=40)),
                ('apellidoDos', models.CharField(max_length=40)),
                ('telefono', models.IntegerField(default=0)),
                ('fecha_nacimiento', models.DateField()),
                ('fotoPerfil', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('descripcion', models.CharField(max_length=250)),
                ('aficiones', models.ManyToManyField(to='appRedSocial.Aficion')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRedSocial.ciudad')),
                ('estadoCivil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRedSocial.estadocivil')),
            ],
        ),
        migrations.CreateModel(
            name='Seguidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seguido', to='appRedSocial.usuario')),
                ('seguidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigos', to='appRedSocial.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Seguidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seguidor', to='appRedSocial.usuario')),
                ('seguidores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='appRedSocial.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('texto', models.CharField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRedSocial.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateField()),
                ('texto', models.CharField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('nombreUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRedSocial.usuario')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRedSocial.post')),
            ],
        ),
    ]
