# Generated by Django 3.1.3 on 2020-11-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedSocial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='contraseña', max_length=8),
        ),
    ]
