# Generated by Django 3.1.3 on 2020-11-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedSocial', '0002_usuario_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fotoPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='appRedSocial/static/img'),
        ),
    ]
