# Generated by Django 3.1.3 on 2020-11-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRedSocial', '0007_auto_20201118_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nombreUsuario',
            new_name='autor',
        ),
    ]
