# Generated by Django 3.1.3 on 2020-11-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedSocial', '0015_auto_20201119_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='aficion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobreMi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
