# Generated by Django 3.1.3 on 2020-11-17 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appRedSocial', '0003_auto_20201117_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='appRedSocial/static/img'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
