# Generated by Django 3.1.3 on 2020-11-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedSocial', '0004_auto_20201117_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='aficiones',
            field=models.ManyToManyField(default=1, to='appRedSocial.Aficion'),
        ),
    ]
