# Generated by Django 3.1.3 on 2020-11-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedSocial', '0010_auto_20201118_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
