# Generated by Django 3.1.3 on 2020-11-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedSocial', '0013_auto_20201119_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aficiones',
            field=models.ManyToManyField(to='appRedSocial.Aficion'),
        ),
    ]
