# Generated by Django 3.1.3 on 2020-11-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedSocial', '0016_auto_20201119_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='aficiones',
            field=models.ManyToManyField(default=0, to='appRedSocial.Aficion'),
        ),
    ]
