# Generated by Django 3.1.3 on 2020-12-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedSocial', '0019_usuario_fotodescripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguidos',
            name='nombreUsuario',
        ),
        migrations.RemoveField(
            model_name='seguidos',
            name='seguidos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='segidores',
            field=models.ManyToManyField(related_name='_usuario_segidores_+', to='appRedSocial.Usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segidos',
            field=models.ManyToManyField(related_name='_usuario_segidos_+', to='appRedSocial.Usuario'),
        ),
        migrations.DeleteModel(
            name='Seguidores',
        ),
        migrations.DeleteModel(
            name='Seguidos',
        ),
    ]
