# Generated by Django 3.1.3 on 2021-01-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedSocial', '0020_auto_20201203_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='post',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
