# Generated by Django 3.1.4 on 2021-01-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedSocial', '0021_auto_20210103_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='usuariosLike',
            field=models.ManyToManyField(default=[0], related_name='likes', to='appRedSocial.Usuario'),
        ),
    ]
