# Generated by Django 3.1.4 on 2021-01-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRedSocial', '0022_post_usuarioslike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='usuariosLike',
            field=models.ManyToManyField(related_name='likes', to='appRedSocial.Usuario'),
        ),
    ]
